import path from "node:path";

/**
 * Files inside `packages/canon/` that the editorial workflow is allowed to
 * propose changes against.
 *
 * Notable exclusions:
 * - `recovered-artifacts/**` — historically authoritative, behaviorally
 *   non-binding; not edited through this workflow.
 * - `examples/**` — illustrative material, edited directly when needed.
 * - `changelog/**` — generated by accepted proposals, not authored through
 *   them.
 * - `proposals/**` — placeholder directory for legacy hand-filed drafts.
 * - `package.json`, `README.md` — packaging / documentation, not canon body.
 */
export const EDITABLE_CANON_FILES = [
  "constitution.md",
  "axioms.md",
  "epistemics.md",
  "constraints.md",
  "voice.md",
  "interaction-modes.md",
  "worldview.md",
  "anti-patterns.md",
  "continuity-facts.yaml",
  "glossary.yaml",
  "manifest.yaml",
] as const;

export type EditableCanonFile = (typeof EDITABLE_CANON_FILES)[number];

export function isEditableCanonFile(value: string): value is EditableCanonFile {
  return (EDITABLE_CANON_FILES as readonly string[]).includes(value);
}

export function resolveCanonPath(canonRoot: string, relPath: string): string {
  if (
    !relPath ||
    relPath.includes("..") ||
    relPath.startsWith("/") ||
    relPath.includes("\\")
  ) {
    throw new Error(`Invalid canon path: ${relPath}`);
  }

  const resolved = path.resolve(canonRoot, relPath);
  const normalizedRoot = path.resolve(canonRoot);
  if (
    resolved !== normalizedRoot &&
    !resolved.startsWith(`${normalizedRoot}${path.sep}`)
  ) {
    throw new Error(`Path escapes canon root: ${relPath}`);
  }

  return resolved;
}

export function canonFileLabel(relPath: string): string {
  switch (relPath) {
    case "constitution.md":
      return "Constitution";
    case "axioms.md":
      return "Axioms";
    case "epistemics.md":
      return "Epistemics";
    case "constraints.md":
      return "Constraints";
    case "voice.md":
      return "Voice";
    case "interaction-modes.md":
      return "Interaction Modes";
    case "worldview.md":
      return "Worldview";
    case "anti-patterns.md":
      return "Anti-Patterns";
    case "continuity-facts.yaml":
      return "Continuity Facts";
    case "glossary.yaml":
      return "Glossary";
    case "manifest.yaml":
      return "Canon Manifest";
    default:
      return relPath;
  }
}
