export {
  approveWitnessAnnotation,
  approveWitnessSynthesis,
  createWitnessAnnotationDraft,
  createWitnessSynthesisDraft,
  getWitnessConsentGate,
  persistWitnessTurnArtifacts,
  rejectWitnessAnnotation,
  rejectWitnessSynthesis,
  type PersistWitnessTurnArtifactsInput,
  type PersistWitnessTurnArtifactsResult,
  type WitnessCompensationEvent,
  type WitnessCompensationLogger,
  type WitnessConsentGate,
} from "../../../packages/orchestration/src/witness/runtime";
